name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_widget_book:
    path: ../
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner:
  widgetbook_generator: ^3.10.0

flutter:
  uses-material-design: true
